export const SITE_URL = "https://xenzee.site";
export const SITE_NAME = "Dzakri Phalosa Nugroho";
export const SITE_DESCRIPTION =
  "Web Developer Pekalongan untuk Laravel, WordPress, CodeIgniter, dashboard admin, company profile, dan IT support. Lihat proyek nyata Dzakri Phalosa Nugroho.";
export const SITE_KEYWORDS = [
  // Nama / identitas
  "Dzakri Phalosa Nugroho",
  "Phalosa Nugroho",
  "Dzakri Nugroho",
  "Zee Developer",
  "xenzee.site",
  // Role utama
  "Web Developer Indonesia",
  "Web Developer Pekalongan",
  "Web Developer Jawa Tengah",
  "Full Stack Developer PHP",
  "Full Stack Developer Indonesia",
  "PHP Developer Indonesia",
  "Frontend Developer Indonesia",
  "Backend Developer Indonesia",
  "Junior Web Developer Indonesia",
  "Junior Developer Pekalongan",
  // Stack teknis
  "Laravel Developer Indonesia",
  "Laravel Developer Pekalongan",
  "WordPress Developer Indonesia",
  "WordPress Developer Pekalongan",
  "CodeIgniter Developer Indonesia",
  "Next.js Developer Indonesia",
  "React Developer Indonesia",
  "Tailwind CSS Developer",
  "Alpine.js Developer",
  "MySQL Developer Indonesia",
  "REST API Developer Indonesia",
  // IT & Administrasi
  "IT Support Indonesia",
  "IT Support Pekalongan",
  "Administrasi Sistem",
  "Operasional IT",
  "Staf IT Pekalongan",
  "Teknisi Komputer Pekalongan",
  "Jaringan Komputer Pekalongan",
  // Jasa / layanan
  "Jasa Pembuatan Website Pekalongan",
  "Jasa Website Murah Pekalongan",
  "Jasa Website UMKM Pekalongan",
  "Jasa Website Company Profile Pekalongan",
  "Jasa Website Toko Online Pekalongan",
  "Jasa Pembuatan Aplikasi Web Indonesia",
  "Jasa Web Developer Freelance Indonesia",
  "Jasa Dashboard Admin",
  "Jasa Integrasi API",
  // Geo — kota-kota sekitar Pekalongan
  "Programmer Pekalongan",
  "Developer Freelance Pekalongan",
  "Jasa Website Jawa Tengah",
  "Web Developer Batang",
  "Web Developer Pemalang",
  "Web Developer Tegal",
  "Web Developer Brebes",
  "Web Developer Kendal",
  "Web Developer Semarang",
  "Web Developer Kajen",
  "Jasa Website Batang",
  "Jasa Website Pemalang",
  "Jasa Website Tegal",
  "Jasa Website Semarang",
  // Status / fresh grad / rekrutmen
  "Fresh Graduate Web Developer",
  "Mahasiswa Informatika Web Developer",
  "Portfolio Mahasiswa Informatika",
  "Web Developer Fresh Graduate Indonesia",
  "Lowongan Web Developer Pekalongan",
  "Hire Web Developer Pekalongan",
  "Cari Web Developer Indonesia",
  "Rekrut Web Developer Indonesia",
  // Portfolio umum
  "Portfolio Web Developer",
  "Portfolio Developer Indonesia",
  "Portfolio PHP Developer",
  "Portofolio Web Developer Indonesia",
  "Portfolio Full Stack Developer",
  "Portfolio Laravel Developer",
  "Portfolio Next.js Developer",
  // Niche / spesifik
  "Website PPOB Indonesia",
  "Aplikasi Kasir Web",
  "Company Profile Website",
  "Dashboard Admin Laravel",
  "Manga Platform Web",
];
